### PR TITLE
docs: Removing tags in readme until fix

### LINKED ISSUE #49: docs: Specifying tagged version does not work in forc.toml
As outlined in the forum post [here](https://forum.fuel.network/t/sway-token-standarts-documentation/3896)

In `forc.toml` `#1` does not work but `#2` does

1. `src20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.2.2" }`

```
Error: failed to find package `src20` in git+https://github.com/FuelLabs/sway-standards?tag=v0.1.1#5a85090678f3a9deb7040424d4ee502d3d9f5bcf
```

2. `src20 = { git = "https://github.com/FuelLabs/sway-standards" }`

```
Fetching src20 git+https://github.com/FuelLabs/sway-standards?default-branch#718d51fdfdbdf4d399c8f281e31462a9f35f0304
Creating a new `Forc.lock` file. (Cause: lock file did not match manifest)
  Adding src20 git+https://github.com/FuelLabs/sway-standards?default-branch#718d51fdfdbdf4d399c8f281e31462a9f35f0304
 Created new lock file at /Users/calldelegation/Projects/Fuel/hello_sway/Forc.lock
 ```

### PR DESCRIPTION
**Pull request by calldelegation**
## Type of change

- Documentation

## Changes

The following changes have been made:

Removing tags in the readme until fix

## Notes

Issue reported in the forum post [here](https://forum.fuel.network/t/sway-token-standarts-documentation/3896)

## Related Issues

Closes #49

### CODE REVIEW

**Review by Braqzen — COMMENTED** [review]
I dislike this because they will keep pulling changes from master. The tags are there for a reason. They can pull master themselves and ignore the tags here until the fix is up

**Comment by bitzoic** [comment]
This suggests we want users to use the master branch which we are strictly discouraging. Users should use the most recent stable releases.

**Review by bitzoic — CHANGES_REQUESTED** [review]
This suggests we want users to use the master branch which we are strictly discouraging. Users should use the most recent stable releases. 

I have made a new release with the `src20` keyword: https://github.com/FuelLabs/sway-standards/releases/tag/v0.3.0

**Comment by calldelegation** [comment]
Thanks for the release fix changed it to `v0.3.0` instead :)

**Review by bitzoic — APPROVED** [review]

**Review by Braqzen — APPROVED** [review]

**Pull request merged**
